packages:
  - 'packages/*'
catalog:
  '@leedomjs/eslint-config-ts': '^0.12.3'
  'bumpp': '^9.5.2'
  'eslint': '8.57.0'
  'lint-staged': '^15.2.10'
  'local-pkg': '^0.5.0'
  'simple-git-hooks': '^2.11.1'
  'tailwindcss': '^3.4.10'
  'typescript': '~5.3.3'
  'unbuild': '^2.0.0'
  'vitest': '^2.0.5'
